sudo: required
services:
    - docker

before_install:
    - docker build -t yeauxda/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true yeauxda/docker-react npm run test -- --coverage